services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: territoire
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teillet.corentin@gmail.com  # Remplace par ton email
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}  # Défini dans ton fichier d'environnement
    ports:
      - "5050:80"
    depends_on:
      - postgis

  territoire-back:
    image: ghcr.io/cteillet/territoire-back:latest
    container_name: territoire-back
    restart: always
    depends_on:
      - postgis
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"


  territoire-front:
    image: ghcr.io/cteillet/territoire-front:latest
    container_name: territoire-front
    restart: always
    depends_on:
      - territoire-back
    environment:
      NEXT_PUBLIC_API_URL: http://territoire-back:8080
    ports:
      - "3000:3000"

  collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=grafana-tms.cteillet.fr
      - GF_SERVER_ROOT_URL=https://grafana-tms.cteillet.fr
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      # sécurité
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200" # tempo
      - "5317:4317" # otlp grpc

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus-config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki-config.yaml

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: "postgis:5432/territoire?sslmode=disable"
      DATA_SOURCE_USER: "admin"
      DATA_SOURCE_PASS: ${PG_ADMIN_PASSWORD}
    ports:
      - "9187:9187"

  waha:
    restart: always
    image: devlikeapro/waha:latest
    # Add "dns" if you have a problem with resolving "web.whatsapp.com"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    ports:
      - '20080:3000/tcp'
    volumes:
      - './config/waha/sessions:/app/.sessions'
      - './config/waha/media:/app/.media'
    environment:
      - WAHA_BASE_URL=https://waha-tms.cteillet.fr
      - WAHA_DASHBOARD_ENABLED=True
      - WAHA_DASHBOARD_USERNAME=admin
      - WHATSAPP_SWAGGER_ENABLED=True
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info
      - WAHA_PRINT_QR=False
      - WAHA_MEDIA_STORAGE=LOCAL
      - WHATSAPP_FILES_LIFETIME=0
      - WHATSAPP_FILES_FOLDER=/app/.media
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WHATSAPP_SWAGGER_PASSWORD=${WHATSAPP_SWAGGER_PASSWORD}

volumes:
  postgis_data:
  grafana_data:
  tempo_data:
