services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: territoire
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teillet.corentin@gmail.com  # Remplace par ton email
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}  # Défini dans ton fichier d'environnement
    ports:
      - "5050:80"
    depends_on:
      - postgis

  territoire-back:
    image: ghcr.io/cteillet/territoire-back:latest
    container_name: territoire-back
    restart: always
    depends_on:
      - postgis
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"


  territoire-front:
    image: ghcr.io/cteillet/territoire-front:latest
    container_name: territoire-front
    restart: always
    depends_on:
      - territoire-back
    environment:
      NEXT_PUBLIC_API_URL: http://territoire-back:8080
    ports:
      - "3000:3000"

volumes:
  postgis_data:
