global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8889']
  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"] # Replace IP with the hostname of the docker container if you're running the container in a separate network
