import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import React from "react";
import {ReduxProvider} from "@/store/provider";
import {Toaster} from "@/components/ui/toaster";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "TMS",
    description: "Generated by create next app",
    icons: [
        "/images/logo.svg",
    ],
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="fr">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ReduxProvider>
            <SidebarProvider>
                <AppSidebar/>
                <main className={"bg-gray-200 w-screen"}>
                    <SidebarTrigger/>
                    {children}
                </main>
                <Toaster/>
            </SidebarProvider>
        </ReduxProvider>
        </body>
        </html>
    );
}
