name: Build and Deploy

on:
  push:
    branches:
      - master  # Change selon ta branche principale

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/cteillet/territoire-back:latest ./territoire-back
          docker push ghcr.io/cteillet/territoire-back:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/cteillet/territoire-front:latest ./territoire-front
          docker push ghcr.io/cteillet/territoire-front:latest

  deploy:
    name: Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_SSH_ID }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.VPS_SSH_ID }}/territoire/"

      - name: Connect to VPS and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_SSH_ID }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/cteillet/territoire-back:latest
            docker pull ghcr.io/cteillet/territoire-front:latest
            cd /home/${{ secrets.VPS_SSH_ID }}/territoire
            docker compose up -d --force-recreate
